### ISSUE TITLE
Не могу удается подключится к библиотеке на Блендере 4.0 

### ISSUE THREAD

**Issue by Sahyk1** [Poly-Haven/polyhavenassets#104]
**Describe the bug**
После установки Адонна на версию Блендера 4.0 не подключается к библиотеке
![sVIn-Hl3Ga0](https://github.com/Poly-Haven/polyhavenassets/assets/164618327/fc83c310-8a89-47bb-88e1-e6ea71fb76e4)

**Additional context**

**Comment by gregzaal** [comment]
Hi, if you're not purchasing the add-on from the [Blender Market](https://blendermarket.com/products/poly-haven-asset-browser) or supporting us on [Patreon](https://www.patreon.com/polyhaven/overview), make sure you follow the installation instructions in the readme carefully. The add-on must be downloaded from the releases page.
