### ISSUE TITLE
Poly Haven not being able to install correctly

### ISSUE THREAD

**Issue by Luizeopm** [Poly-Haven/polyhavenassets#107]
![Sem título](https://github.com/Poly-Haven/polyhavenassets/assets/150378684/becea552-8abf-4a9d-af15-fad6c1147bba)

Poly haven cannot be enabled. It's my first time here so if anyone can help me that'd mean a lot to me

**Comment by tangni** [comment]
unzip之后把polyhavenassets-1.1.7改成polyhavenassets_1

**Comment by drax-uk** [comment]
I have the same issue. 1.1.7 version with Blender 4.1.

**Comment by gregzaal** [comment]
Where did you download the zip file that you installed?

**Comment by drax-uk** [comment]
Hi Greg, from the repo 
https://github.com/Poly-Haven/polyhavenassets/archive/refs/tags/v1.1.7.zip

**Comment by gregzaal** [comment]
@drax-uk Please follow the install instructions to install it correctly and avoid errors like this: https://github.com/Poly-Haven/polyhavenassets?tab=readme-ov-file#installation
