### ISSUE TITLE
Set up Displacement is Grayed Out 

### ISSUE THREAD

**Issue by ConstantChange** [Poly-Haven/polyhavenassets#11]
Even if I have ever render option checked. Not sure what's left to do here to get it active. Blender 3.2.1

It says to create modifiers. What modifiers am i creating to get this button to become active?

![image](https://user-images.githubusercontent.com/72226015/189054004-cf6ad5f4-5ab1-41a0-85b0-55c987a711cf.png)

It does become an option if I switch to Cycles (could say that in the tooltip) but even after clicking it there is no change to the material.

![image](https://user-images.githubusercontent.com/72226015/189054652-f9970f42-57c2-4555-919e-c1ea8bdf2c92.png)

**Comment by gregzaal** [comment]
Displacement is only usable in Cycles, and you'll only be able to see it in rendered shading mode.

**Comment by ConstantChange** [comment]
Ok not to beat this horse, but When i apply say, "Aerial Rocks" and look at it, without changing anything, in the rendered shading mode in cycles, this is what I get

![image](https://user-images.githubusercontent.com/72226015/189198470-129f61f6-ab3a-4683-8b9c-91132023c6de.png)


Is this the expected behavior?
