### ISSUE TITLE
The addon cannot be activated

### ISSUE THREAD

**Issue by susienka** [Poly-Haven/polyhavenassets#117]
**Describe the bug**
I install the addon as it should be, but then I can't turn it on.

![image](https://github.com/Poly-Haven/polyhavenassets/assets/171314963/70e064e7-1ca1-4f81-8dd6-1feb6e0cc9c7)

**Comment by gregzaal** [comment]
Hi, if you're not purchasing the add-on from the [Blender Market](https://blendermarket.com/products/poly-haven-asset-browser) or supporting us on [Patreon](https://www.patreon.com/polyhaven/overview), make sure you follow the installation instructions in the readme carefully. The add-on must be downloaded from the releases page.
