### ISSUE TITLE
Getting error after enabling proxy

### ISSUE THREAD

**Issue by Leroy-X** [Poly-Haven/polyhavenassets#12]
I couldn't update via normal network, so I turned on the vpn system (global) proxy, but got an error. Screenshot below:
![20220909111317](https://user-images.githubusercontent.com/13515498/189264614-06c0ce41-dd84-4528-b488-a04b974b0c78.png)

**Comment by gregzaal** [comment]
It's unlikely I'm going to be able to help with this, but I can give it a shot. What VPN service are you using, which country are you from, and which country are you connecting to through the VPN?

**Comment by Leroy-X** [comment]
Hi, thank you very much for your quick reply. I am in China, and it is easy to get an error when downloading a large file from the normal network, even if I check CDN and SSL in the configuration. I use [v2rayN](https://github.com/2dust/v2rayN) for proxying. I tested ports in multiple countries, such as US, Korea, Singapore, etc.

**Comment by gregzaal** [comment]
Hi again. Sorry, I am unable to assist you with this issue as it is a connection issue between you and our servers. I cannot reproduce the problem here. There are some other Chinese users who had similar problems, some of which magically resolved themselves after a few days. If you cannot solve the problem, feel free to contact Blender Market support for a refund.

**Comment by Leroy-X** [comment]
Hi, using [environment variables](https://docs.cloudfoundry.org/cf-cli/http-proxy.html#:~:text=hostname%3Aport%0Aexport%20%24https_proxy-,Set%20https_proxy%20in%20Windows,-To%20set%20the) solved the proxy problem. It may be caused by Blender not supporting http. Proxy software is a modified system proxy setting. Hope you can put it on the [trouble](https://github.com/Poly-Haven/polyhavenassets/wiki/Troubleshooting) page to help more people.

By the way, some images were found to be broken. For example, half normal and half black. It should be a problem caused by unstable download. Hope to add file integrity check later.
