### ISSUE TITLE
Error when I try to download the content !

### ISSUE THREAD

**Issue by windybut** [Poly-Haven/polyhavenassets#13]
![PolyHavenError](https://user-images.githubusercontent.com/32416093/189356568-e58908c4-3120-4624-936a-9cb1563b4e0b.jpg)

I am no programmer but I think the error occurs while getting the asset list.  I have enclosed a cropped picture showing the error message.  I have follow the Docs on blender market but none of the troubleshooting fixes work for me.

I am using Blender 3.2.2 which I updated it yesterday.  I am on windows 11.   I downloaded the latest version of your software from here on github.

I hope the info I have in this message helps you to find a fix.

Windybut

**Comment by gregzaal** [comment]
Hi,

It looks like you missed a step in the install instructions (renaming the add-on folder)
