### ISSUE TITLE
assets downloaded successfully, but none is shown in the browser 

### ISSUE THREAD

**Issue by carmo2011** [Poly-Haven/polyhavenassets#14]
![image](https://user-images.githubusercontent.com/87646057/189393346-8df71ea0-4a9d-4e1c-b0b0-6414d5c81311.png)
 as the title said, could you help to fix it? why it happened?
blender version is 3.2
thanks

**Comment by gregzaal** [comment]
Hi, please check the troubleshooting page for possible solutions for this issue: https://github.com/Poly-Haven/polyhavenassets/wiki/Troubleshooting#asset-browser-is-empty
