### ISSUE TITLE
Error on Install 

### ISSUE THREAD

**Issue by glaseagle** [Poly-Haven/polyhavenassets#15]
I was dumb and unzipped the folder and tried to install the python scripts but then when I got wise I kept getting these errors which are the same as the files which I deleted from the addons folder.
![Screenshot (53)](https://user-images.githubusercontent.com/113222694/189466424-9eb3fdfe-abc3-4b0e-970e-c1387f4a7287.png)

**Comment by gregzaal** [comment]
Sorry, this add-on requires blender 3.2 or later.
