### ISSUE TITLE
HDRI World Missing the Poly Haven Resolution Drop Down

### ISSUE THREAD

**Issue by mpwillner** [Poly-Haven/polyhavenassets#17]
Blender Version: 3.4
Render Engine: Cycles - GPU Compute - Experimental

I have the Poly Haven plug in installed and working.  However, as in your video, there is no Resolution Drop Down in the World tab after the HDRI has been applied. s.
![Blender Screenshot 2022-09-21 105242](https://user-images.githubusercontent.com/3492281/191576283-4d3fffe4-02c6-4103-89c1-665b71398e1a.png)

Thank you.

**Comment by gregzaal** [comment]
Replying to your support ticket on the Blender Market.
