### ISSUE TITLE
Allow selection of assets downloaded via NextCloud for use

### ISSUE THREAD

**Issue by Patchnote-v2** [Poly-Haven/polyhavenassets#18]
I've downloaded assets using the NextCloud access, and it would be incredibly convenient (and easier on your guys' bandwidth) to be able to select the folder that already contains what I've downloaded via NextCloud.  That way not only do I not have to download the initial 3.3GB of data, but I also don't have to maintain duplicates.

My best uneducated guess to approach this would be to have allow a user to set the root folder, then instead of calling something like `download_file(url, hdr_file)`, it instead checks for a root folder and checks if the file exists there first.  This is only from 10 minutes of poking around the code so I'm sure I'm underestimating the complexity entirely.

**Comment by gregzaal** [comment]
Hi :)

The folder structure that the add-on uses is completely different from the way we have nextcloud set up. They're sort of two different solutions to a similar problem, the one tailored more to Blender users while the other can be used for any software.

I don't think it's within the scope of the project to try and get these two systems to play nicely together, sorry, rather use one or the other.
