### ISSUE TITLE
Addon related questions

### ISSUE THREAD

**Issue by BetterTWL** [Poly-Haven/polyhavenassets#20]
Sorry,The PolyHaven addon is having a major problem! help!help!😖
-----------------------------------------------------------------------------------------------------------------
**1.File:** polyhavenassets-1.0.6.zip
**2.Blender Version:** 3.3.0
**3.Error message:**
`Traceback (most recent call last):
  File "D:\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'polyhavenassets-1'`

**✅4.Full content:** https://pastebin.com/u/BetterTWL/1/v405wAux

**Comment by gregzaal** [comment]
Hi, it looks like you did not read the instructions carefully :) If you download it here on GitHub instead of purchasing it, you need to rename the installed folder manually.

**Comment by BetterTWL** [comment]
How?
