### ISSUE TITLE
Poly Haven Blender Asset Browser Cannon Import Error

### ISSUE THREAD

**Issue by mpwillner** [Poly-Haven/polyhavenassets#21]
I recently tried to drag and drop the Cannon (Models > Cannon_01) and when it came in, the Collection was not separated into parts. I then went to Sketchfab and downloaded a similar cannon which came with all the parts correctly separated with empties. I've attached two screen shots. 

Blender 3.3.0 on latest Windows 10
![Poly Haven Screenshot 2022-10-04 102952](https://user-images.githubusercontent.com/3492281/193887634-b8e484b7-ab8c-451c-9bd8-5e5c98745f53.png)
![Poly Haven Screenshot 2022-10-04 102916](https://user-images.githubusercontent.com/3492281/193887660-8c1cd49f-1c69-4555-8acc-66b8cbb22111.png)

**Comment by gregzaal** [comment]
Assets are appended as collection instances. If you need to edit it, simply press **Ctrl-A > Make instances real**. More usage info on the wiki: https://github.com/Poly-Haven/polyhavenassets/wiki

**Comment by mpwillner** [comment]
Thank you.
*Mark Willner*
