### ISSUE TITLE
HDRI node setup "too proprietary"

### ISSUE THREAD

**Issue by benthillerkus** [Poly-Haven/polyhavenassets#25]
The generated node setup for HDRIs on the world material moves the texture inside a node group.
This is problematic, because it means you cannot use the Sun Position add-on (ships with Blender per default).

One of the features of the sun position add-on is synching the HDRI and a sun lamp, which is needed in Eevee to get shadows.

I suppose there is probably a way to maintain current functionality without breaking compat?

**Comment by gregzaal** [comment]
This seems more like an issue with the Sun Position add-on, I don't think we should avoid using core Blender features like node groups just becuase some other add-ons don't bother to handle them.
