### ISSUE TITLE
how to change HDRI resolution?

### ISSUE THREAD

**Issue by Wanderhuze** [Poly-Haven/polyhavenassets#26]
Hello! I download 4k and 8k, but the scene is still 1k resolution. What needs to be done to apply 4k or 8k?
![image](https://user-images.githubusercontent.com/78296100/196911311-d6718843-727f-4efa-b46f-7e2e5faa5ef6.png)

**Comment by gregzaal** [comment]
Hi :) I can confirm this works fine for me here, with the same HDRI.

Are there any error messages shown in your system console / terminal? I need more information to understand what it happening.

**Comment by Wanderhuze** [comment]
> 

No error messages in the console. Here is an example of my actions:
1. Created a cube.
2. Assigned texture aerial_beach_01
![image](https://user-images.githubusercontent.com/78296100/196964544-00ed72bf-293c-4710-b8ad-786406c57380.png)
3. The file has 4k in the name but I haven't uploaded 4k yet.
![image](https://user-images.githubusercontent.com/78296100/196967926-93a36812-b415-41b2-81a0-066a422e9f55.png)
and these files are not on the disk
![image](https://user-images.githubusercontent.com/78296100/196967703-c50053b3-e306-446e-9c2a-3c32dc46f8e6.png)
4. I download 4k and try to apply but nothing happens. Absolutely nothing. 
![image](https://user-images.githubusercontent.com/78296100/196968820-8d696630-b565-4cc2-b670-f8d10f2794fb.png)
5.  I download 2k and try to apply but nothing happens.
![image](https://user-images.githubusercontent.com/78296100/196969140-ae9128f2-99cc-4240-9880-22b8c996321c.png)

console still has no error messages
![image](https://user-images.githubusercontent.com/78296100/196969393-ec855dd5-18fb-402e-8e66-83e3a844bc3f.png)

what am I doing wrong? )

**Comment by gregzaal** [comment]
Maybe there is some confusion happening here, everything looks like it's working correctly.

In your screenshot `3.`, the "file name" there is not actually the file name, it's the datablock name in Blender, which happens to be "..._4k.png". This doesn't mean the file it's referencing has the same name, it's simply the name of the [datablock](https://docs.blender.org/manual/en/latest/files/data_blocks.html).

You can check the actual file name by opening that image in the image editor and inspecting the image properties:

![2022-10-21_06-26-29](https://user-images.githubusercontent.com/5604661/197111914-cf80192c-8258-406f-a601-7be53f542d8c.jpg)

Here's a little screen recording of the behavior. Notice how the datablock name doesn't change, but the actual file path and the image resolution does change:

https://user-images.githubusercontent.com/5604661/197112314-6657452b-1282-4c2a-9b2a-c4095acb826a.mp4
