### ISSUE TITLE
Blender 3.3.1 - no structure for assets generated

### ISSUE THREAD

**Issue by max13126** [Poly-Haven/polyhavenassets#27]
Blender 3.3.1 does not create the structure for the asset browser. Restartet Blender several times - all assets are still filed unsorted under "all" while the subcatalog named "Poly Haven" stays empty.
Also the displacement set up for the materials is inactive.

**Comment by gregzaal** [comment]
Hi,

I'll need more information to understand this issue. Please provide an exact list of steps (starting from clean factory-defaults) to reproduce the problem, so I can investigate further.

What will also be necessary is a [console](https://i.stack.imgur.com/hK3bu.jpg)/[terminal](https://docs.blender.org/manual/en/latest/advanced/command_line/launch/index.html) log after running into the issue.

**Comment by max13126** [comment]
Hi,
I installed the PlugIn following your Installation Video step by step.
Just installed the blender 3.3.1 because your plugin won’t work with my 3.1 version.

This ist the logfile:

Read prefs: C:\Users\Alexander.Boehm\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend
Registered DECALmachine 2.6.5 with 0 decal libraries, 0 trim sheet libraries and 0 atlases. PIL 9.0.1 Image Module: C:\\Users\\Alexander.Boehm\\AppData\\Roaming\\Python\\Python310\\site-packages\\PIL\\_imaging.cp310-win_amd64.pyd
Decals, Trimsheets and Atlases are located in H:\Programs\Blender\DECALmachine Assets\
WARN (bpy.rna): C:\Users\blender\git\blender-v330\blender.git\source\blender\python\intern\bpy_rna.c:1340 pyrna_enum_to_py: current value '0' matches no enum in 'Scene', 'Scene', 'userdecallibs'
WARNING: No valid Decal Libraries registered!
WARN (bpy.rna): C:\Users\blender\git\blender-v330\blender.git\source\blender\python\intern\bpy_rna.c:1340 pyrna_enum_to_py: current value '0' matches no enum in 'Scene', 'Scene', 'trimsheetlibs'
WARNING: No Trimsheet Libraries registered!

**Comment by gregzaal** [comment]
There don't seem to be any error messages relating to our add-on in there. Unfortunately I cannot help any further without being able to reproduce the issue myself, for which I need an exact list of steps starting from factory defaults.

**Comment by gregzaal** [comment]
Closing this issue as I can't help without further information.
