### ISSUE TITLE
error Traceback

### ISSUE THREAD

**Issue by sloowmaker** [Poly-Haven/polyhavenassets#28]
![image](https://user-images.githubusercontent.com/116822436/198322059-48b5ecde-ad65-4557-8f0c-80b9d8d2a4e7.png)

I just bought the addon, but I am new to both blender and github, so I am a little confused. Might be that I am doing something wrong here, but if you can help me, that would be great.

**Comment by gregzaal** [comment]
Hi, this add-on is only compatible with Blender 3.2 or later.

**Comment by sloowmaker** [comment]
Hi gregzaal, thank you for helping out and sorry for my mistake. I assumed I was using the latest version, but I clearly wasn't.
