### ISSUE TITLE
Download only preview images of the assets

### ISSUE THREAD

**Issue by rajq123** [Poly-Haven/polyhavenassets#29]
We rarely use 10% of what is available and then reuse them in each project. So my suggestion is to only download preview images and then download the assets if the user want it as it will save hard disk space. Also helpful if you show/suggest similar assets if we click on any textures. Also you can also add option to submit render image of the project where the asset is used so another user can better visualize the asset usage, it is a community neural learning (hahaha).

**Comment by gregzaal** [comment]
This is something we plan to implement eventually, but as the entire asset library is only 3gb at the moment it's not a high priority.
