### ISSUE TITLE
Error Activating Add-On

### ISSUE THREAD

**Issue by DeepD1ver** [Poly-Haven/polyhavenassets#3]
When I try to activate the add-on, I get this error:
![polyhavenasset_error](https://user-images.githubusercontent.com/51963623/186225407-e01f574d-4346-4264-aa82-16961a90199d.PNG)

I tried restarting, as well as making sure the asset library (Poly Haven) folder was created.

Cheers,
Bruce

**Comment by gregzaal** [comment]
Hi, it looks like you skipped a step in the install instructions (renaming the folder to remove the version number) 🙂
