### ISSUE TITLE
Changing HDRI resets Mist pass values

### ISSUE THREAD

**Issue by optimus007** [Poly-Haven/polyhavenassets#30]
Noticed mist quality was really bad after a render then realised changing the hdri using drag drop had reset this values too

Desired result : maintain the values while changing the hdri as this is related to camera

To reproduce
- enable mist pass in camera/render layers
- change value in world settings
- drag drop another hdri 
- value has reset

**Comment by gregzaal** [comment]
Currently the only way that I'm aware of that Blender supports HDRIs in the asset browser is to have the whole world datablock marked as an asset. This includes the whole node tree and any other world settings. Unfortunately this is not something that we can fix now.
