### ISSUE TITLE
Python Error When Trying to Fetch Assets from Polyhaven.com

### ISSUE THREAD

**Issue by no185** [Poly-Haven/polyhavenassets#34]
After I downloaded the ZIP file and set up the asset library, I get a python error when trying to fetch the assets. Here is the exact error:
![image](https://user-images.githubusercontent.com/59538980/204074194-e5cd4c43-f26d-4726-93a8-e7f25b5da334.png)

**Comment by DrDillis** [comment]
Same here same error here.

"Python: Traceback (most recent call last):
  File "C:\Users\Computer\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\polyhavenassets-main\operators\pull_from_polyhaven.py", line 260, in execute
    error, assets = get_asset_list(self.asset_type)
  File "C:\Users\Computer\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\polyhavenassets-main\utils\get_asset_list.py", line 15, in get_asset_list
    verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify
KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'
"

Using blender 3.3.1 LTS on Windows 10.

**Comment by tzy-tp** [comment]
Locate the Blender Addons Folder
Windows: %appdata%\Blender Foundation\Blender\x.x\scripts\addons\
Mac: ~/Library/Application Support/Blender/x.x/scripts/addons/
Linux: ~/.config/blender/x.x/scripts/addons/
Rename the installed folder from polyhavenassets-x.x.x to just polyhavenassets without the version number at the end.

In my case it was named polxhavenassets-main. You just have to change it to polxhavenassets and it works.

**Comment by gregzaal** [comment]
If you're going to download the add-on from GitHub instead of purchasing it, please read the [installation instructions](https://github.com/Poly-Haven/polyhavenassets#installation) very carefully.
