### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by Sulivar** [Poly-Haven/polyhavenassets#36]
I have the following error message when I try to activate the addon.

Traceback (dernier appel le plus récent) :
  Fichier "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\addon_utils.py", ligne 382, ​​dans enable
    mod.register()
  Fichier "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\polyhavenassets-main\__init__.py", ligne 104, dans le registre
    addon_updater_ops.register(bl_info)
  Fichier "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\polyhavenassets-main\addon_updater_ops.py", ligne 1436, dans le registre
    bpy.utils.register_class(cls)
ValueError : register_class(...) : déjà enregistré en tant que sous-classe 'AddonUpdaterInstallPopup'

**Comment by gregzaal** [comment]
If you're going to install through github instead of purchasing it, please read the instructions carefully.

**Comment by Sulivar** [comment]
What was done, after three attempts I managed to go a little further but I encounter another error when I click on Fetch Asset

Python: Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\polyhavenassets-main\operators\pull_from_polyhaven.py", line 260, in execute
    error, assets = get_asset_list(self.asset_type)
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\polyhavenassets-main\utils\get_asset_list.py", line 15, in get_asset_list
    verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify
KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'

The file that he does not find well was renamed as in the instructions, so I give up for this one but I keep it under the corner of my eye in case of an update for the installation.
