### ISSUE TITLE
Only 45 assets downloading

### ISSUE THREAD

**Issue by rojharris** [Poly-Haven/polyhavenassets#37]
**Describe the bug**
On clicking 'Fetch Assets' only 45 come down. 8 HDRIs and some materials and models. Changing server settings in prefs makes no difference. No firewalls or virus software on machine.

**Console log**
Start blender from a command prompt/terminal (https://docs.blender.org/manual/en/latest/advanced/command_line/launch/index.html), reproduce the issue and paste the entire console output here:

```
Last login: Thu Dec  1 12:48:39 on console
rogerharris@Rogers-MBP-2 ~ % cd /Applications/Blender.app/Contents/MacOS
./Blender
Read prefs: /Users/rogerharris/Library/Application Support/Blender/3.3/config/userpref.blend
3.03
DazToBlender: loaded, version 2022.2.17.40
DazToBlender: Default Intermediate Folder path: "/Users/rogerharris/Documents/DAZ 3D/Bridges/Daz To Blender/Exports".
blenderkit addon: Verbose is enabled
blenderkit addon: Read in JSON settings from file
Start generating Libraries...
Generated Icons in 0.049 seconds.
Library Size: 335
blenderkit updater: Running background check for update
blenderkit addon: Starting background checking thread
blenderkit addon: Checking for update now in background
blenderkit addon: Checking for update function
blenderkit addon: Read in JSON settings from file
blenderkit addon: Determined it's not yet time to check for updates
blenderkit addon: Aborting check for updated, check interval not reached
blenderkit addon: Finished check update, doing callback
blenderkit addon: Running background update callback
blenderkit addon: BG thread: Finished check update, no callback
blenderkit INFO: Daemon server starting on address http://127.0.0.1:62485, log file for errors located at: /Users/rogerharris/blenderkit_data/daemon/daemon-62485.log [12:55:15.874, daemon_lib.py:261]
blenderkit INFO: Daemon is running! [12:55:16.771, timer.py:82]
blenderkit INFO: Connected to www.blenderkit.com [12:55:16.771, daemon_lib.py:154]
Info: Downloaded 0 assets

```

**To Reproduce**
Steps to reproduce the behavior, starting from an empty scene in Blender:
1. Go to 'Asset Manager'
2. Click on P'oly Haven'
3. Click on 'Fetch Assets'

**Expected behavior**
I expect lots of assets to download

**Screenshots**

**Additional context**
My Blender asset library is on an iCloud drive so I can share assets with my PC. This behaviour happens on both mac and PC.

**Comment by gregzaal** [comment]
I'm unable to reproduce this issue. Could you try delete your entire asset library folder and download it again?

Then, if the behavior is the same, can you try downloading to a different drive and see if that's the issue?
