### ISSUE TITLE
Only info.json and thumbnail.webp  can be downloaded

### ISSUE THREAD

**Issue by 2650023661** [Poly-Haven/polyhavenassets#4]
blender3.2.2， win11

**Comment by gregzaal** [comment]
Hi, what country are you located in? Are there any errors printed in the console when you click the fetch button? I need more information to investigate this.

**Comment by 2650023661** [comment]
Hello, my region is China, I can open polyhaven.com and download the file, when I click the "fetch" button, the progress bar in the lower left corner downloads normally, and there are no errors in the console, after the download is 100%, reopen blender , the assets are not displayed, the folder path is only info.json and thumbnail.webp。But another friend of mine can download normally。——from google translate

**Comment by gregzaal** [comment]
I believe I know how to resolve the issue. Could you send me a full traceback, the whole error message (what you shared above is just a part of it). To do this, you can delete any asset folders in your library that it might have made, and then start Blender from a command prompt [like this](https://transfer.sh/XQ1951/2022-08-22_16-52-19_explorer.mp4). Click the "Fetch assets" button, and then copy paste the entire console output here please :)

I need to know which lines are throwing that error precisely.

**Comment by 2650023661** [comment]
Thank you for your reply.We can't repeat yesterday's problems today. I can successfully use this plug-in today. It can be downloaded normally.

`Microsoft Windows [Version 10.0.19044.1618]
(c) Microsoft Corporation。保留所有权利。

C:\Users\Administrator\Desktop\blender-3.2.2-windows-x64>.\blender.exe
Read prefs: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\config\userpref.blend
Warning: Could not find a matching GPU name. Things may not behave as expected.
Detected OpenGL configuration:
Vendor: VMware, Inc.
Renderer: SVGA3D; build: RELEASE;  LLVM;
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "abandoned_tank_farm_04.blend"
Info: Saved "abandoned_tank_farm_04.blend"

Blender quit
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "abandoned_hopper_terminal_04.blend"
Info: Saved "abandoned_hopper_terminal_04.blend"

Blender quit
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Total files 2 | Changed 1 | Failed 0
Info: Saved "abandoned_hopper_terminal_01.blend"
Info: Saved "abandoned_hopper_terminal_01.blend"

Blender quit
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "abandoned_factory_canteen_02.blend"
Info: Saved "abandoned_factory_canteen_02.blend"

Blender quit
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "abandoned_church.blend"
Info: Saved "abandoned_church.blend"
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Info: Saved "abandoned_waterworks.blend"
Info: Saved "abandoned_waterworks.blend"

Blender quit
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Info: Total files 2 | Changed 1 | Failed 0

Blender quit
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Saved "abandoned_pathway.blend"
Info: Saved "abandoned_pathway.blend"
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "abandoned_hall_01.blend"
Info: Saved "abandoned_hall_01.blend"

Blender quit

Blender quit
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "abandoned_tank_farm_05.blend"
Info: Saved "abandoned_tank_farm_05.blend"

Blender quit
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "abandoned_slipway.blend"
Info: Saved "abandoned_slipway.blend"
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)

Blender quit
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Total files 2 | Changed 1 | Failed 0
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "abandoned_games_room_02.blend"
Info: Saved "abandoned_games_room_02.blend"
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Info: Total files 2 | Changed 1 | Failed 0
Saved "abandoned_tank_farm_03.blend"
Info: Saved "abandoned_tank_farm_03.blend"

Blender quit
Info: Total files 2 | Changed 1 | Failed 0
Saved "abandoned_parking.blend"
Info: Saved "abandoned_parking.blend"

Blender quit
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Warning: Tag 'backplates' already present for given asset
Info: Saved "abandoned_hopper_terminal_03.blend"

Blender quit
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Saved "abandoned_hopper_terminal_03.blend"
Info: Saved "abandoned_tank_farm_02.blend"
Info: Saved "abandoned_tank_farm_02.blend"
Info: Total files 2 | Changed 1 | Failed 0
Info: Total files 2 | Changed 1 | Failed 0
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0

Blender quit
Info: Saved "abandoned_greenhouse.blend"Info: Saved "abandoned_factory_canteen_01.blend"
Info: Saved "abandoned_factory_canteen_01.blend"

Info: Saved "abandoned_greenhouse.blend"

Blender quit
Info: Saved "abandoned_tank_farm_01.blend"
Info: Saved "abandoned_tank_farm_01.blend"

Blender quit

Blender quit

Blender quit
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "abandoned_games_room_01.blend"
Info: Saved "abandoned_games_room_01.blend"

Blender quit
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "abandoned_hopper_terminal_02.blend"
Info: Saved "abandoned_hopper_terminal_02.blend"

Blender quit
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "abandoned_workshop_02.blend"
Info: Saved "abandoned_workshop_02.blend"
Info: Saved "abandoned_workshop.blend"
Info: Saved "abandoned_workshop.blend"

Blender quit

Blender quit
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "aerodynamics_workshop.blend"
Info: Saved "aerodynamics_workshop.blend"

Blender quit
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Saved "alps_field.blend"
Info: Saved "alps_field.blend"
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "ahornsteig.blend"
Info: Saved "ahornsteig.blend"

Blender quit

Blender quit
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "auto_service.blend"
Info: Saved "auto_service.blend"
Info: Saved "art_studio.blend"
Info: Saved "art_studio.blend"
Info: Saved "aircraft_workshop_01.blend"
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Saved "aircraft_workshop_01.blend"

Blender quit
Info: Total files 2 | Changed 1 | Failed 0

Blender quit
Info: Saved "amphitheatre_zanzibar_fort.blend"
Info: Saved "amphitheatre_zanzibar_fort.blend"

Blender quit
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Saved "air_museum_playground.blend"
Info: Saved "air_museum_playground.blend"
Info: Total files 2 | Changed 1 | Failed 0

Blender quit
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Info: Saved "altanka.blend"
Info: Saved "altanka.blend"

Blender quit

Blender quit
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "aft_lounge.blend"
Info: Saved "aft_lounge.blend"

Blender quit
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "artist_workshop.blend"
Info: Saved "artist_workshop.blend"

Blender quit
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "arboretum.blend"
Info: Saved "arboretum.blend"

Blender quit
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "adams_place_bridge.blend"
Info: Saved "adams_place_bridge.blend"

Blender quit
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "aristea_wreck.blend"
Info: Saved "aristea_wreck.blend"

Blender quit
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "anniversary_lounge.blend"
Info: Saved "anniversary_lounge.blend"

Blender quit
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "autumn_crossing.blend"
Info: Saved "autumn_crossing.blend"

Blender quit
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "approaching_storm.blend"
Info: Saved "autoshop_01.blend"
Info: Saved "approaching_storm.blend"
Info: Saved "autoshop_01.blend"

Blender quit

Blender quit
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "autumn_forest_02.blend"
Info: Saved "autumn_forest_02.blend"

Blender quit
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "autumn_ground.blend"
Info: Saved "autumn_ground.blend"
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)

Blender quit
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "autumn_forest_03.blend"
Info: Saved "autumn_forest_03.blend"

Blender quit
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "aviation_museum.blend"
Info: Saved "aviation_museum.blend"

Blender quit
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "aviation_museum_hill.blend"
Info: Saved "aviation_museum_hill.blend"

Blender quit
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "beach_parking.blend"
Info: Saved "beach_parking.blend"

Blender quit
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "balcony.blend"
Info: Saved "balcony.blend"
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)

Blender quit
Cancelled thumbnail.webp mid-download
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Cancelled autumn_park_1k.hdr mid-download
Cancelled thumbnail.webp mid-download
Cancelled belfast_open_field_1k.hdr mid-download
Cancelled autumn_hockey_1k.hdr mid-download
Cancelled bell_park_pier_1k.hdr mid-download
Cancelled autumn_meadow_1k.hdr mid-download
Cancelled belfast_sunset_1k.hdr mid-download
Cancelled thumbnail.webp mid-download
Cancelled bell_park_dawn_1k.hdr mid-download
Cancelled autumn_road_1k.hdr mid-download
Cancelled belfast_farmhouse_1k.hdr mid-download
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Blender 3.2.2 (hash bcfdb14560e7 built 2022-08-02 23:41:46)
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "ballroom.blend"
Info: Saved "ballroom.blend"
Cancelled thumbnail.webp mid-download
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend

Blender quit
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "autumn_forest_01.blend"
Info: Saved "autumn_forest_01.blend"

Blender quit
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Read blend: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\polyhavenassets\utils\hdri_template.blend
Info: Total files 2 | Changed 1 | Failed 0
Info: Total files 2 | Changed 1 | Failed 0
Info: Saved "autumn_forest_04.blend"
Info: Saved "autumn_forest_04.blend"
Info: Saved "bathroom.blend"
Info: Saved "bathroom.blend"

Blender quit

Blender quit
Info: Downloaded 67 assets

`

**Comment by gregzaal** [comment]
Interesting, thanks for checking! I have a few other users with similar issues, I'll see if they can help debug it.
