### ISSUE TITLE
Addon activation error

### ISSUE THREAD

**Issue by Igrom4ik** [Poly-Haven/polyhavenassets#40]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'polyhavenassets-1'

**Comment by gregzaal** [comment]
Hi,

If you're not purchasing the add-on from the [Blender Market](https://blendermarket.com/products/poly-haven-asset-browser) or supporting us on [Patreon](https://www.patreon.com/polyhaven/overview), make sure you follow the installation instructions in the readme carefully - it seems you did not rename the installed folder.
