### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by SimonBruna** [Poly-Haven/polyhavenassets#43]
**Describe the bug**

I installed this add-on with official Poly Haven video. When i press Fetch assets it gives me some python error. I have zero experience in programming so i have no idea what it means,

**Console log**
Start blender from a command prompt/terminal (https://docs.blender.org/manual/en/latest/advanced/command_line/launch/index.html), reproduce the issue and paste the entire console output here:

Havent figured this out. Im not porgrammer and i dont know how to make this happen even with tutorial. Im just a 3D artist.
```
PASTE CONSOLE OUTPUT HERE
```

**To Reproduce**
Steps to reproduce the behavior, starting from an empty scene in Blender:

**Expected behavior**

I expected it to work maybe? :D

**Screenshots**
![Snímek obrazovky 2022-12-26 173220](https://user-images.githubusercontent.com/79140068/209567985-7788b661-e345-450b-8555-7e02cecb6a35.png)

**Additional context**

**Comment by gregzaal** [comment]
Hi,

If you're not purchasing the add-on from the [Blender Market](https://blendermarket.com/products/poly-haven-asset-browser) or supporting us on [Patreon](https://www.patreon.com/polyhaven/overview), make sure you follow the installation instructions in the readme carefully - it seems you did not rename the installed folder.
