### ISSUE TITLE
Support correcting asset image paths if user moves their library

### ISSUE THREAD

**Issue by qaraluch** [Poly-Haven/polyhavenassets#46]
Moved downloaded assets to another dir. Updated path in Blender's File Path's Asset Libraries. In addon preferences there is updated path to assets. 
Adding for example HDRI asset to the scene the path to the asset is not correct (not updated). The scen has characteristic pink world texture.  You have to manually find correct dir path to the asset in order to work.

No console outputs. 

The workaround is re-download all assets (~ 4 GB of data).

**Comment by gregzaal** [comment]
Currently this is not supported, indeed you have to redownload the library if you decide to move it. But potentially in a future release we might be able to add a function to revalidate the library in various ways.

**Comment by gregzaal** [comment]
Forgot to update you here, Revalidation was added in the last release :)
