### ISSUE TITLE
Can't activate the plugin

### ISSUE THREAD

**Issue by jean-bombeurre** [Poly-Haven/polyhavenassets#49]
Hey there, I just bought your plugin but I can't activate the plugin.

Here's below the error.

Can you help me please?

![bug](https://user-images.githubusercontent.com/123119594/213550939-5eb10514-aa5a-4c23-a208-2247530161f5.png)

**Comment by gregzaal** [comment]
Hi there, the minimum required blender version is 3.2, you'll need to update blender to a more recent version to use this add-on.
