### ISSUE TITLE
Make library name case insensitive

### ISSUE THREAD

**Issue by CColdblender** [Poly-Haven/polyhavenassets#51]
![grafik](https://user-images.githubusercontent.com/124585352/216978973-1ec5a611-64f4-4589-9913-56f0db306b0b.png)

**Comment by gregzaal** [comment]
Hi, you need to name it exactly `Poly Haven`, not `poly haven` or `Poly haven`. I'll make this case insensitive in the next release to avoid this kind of frustration :)
