### ISSUE TITLE
I Get THis Report When I Try To Enable It

### ISSUE THREAD

**Issue by RbBadGuy** [Poly-Haven/polyhavenassets#52]
![image_2023-02-07_223451396](https://user-images.githubusercontent.com/85963793/217347161-c090d505-f37b-4ef2-a7a2-101e64038075.png)

**Comment by gregzaal** [comment]
Hi,

If you're not purchasing the add-on from the [Blender Market](https://blendermarket.com/products/poly-haven-asset-browser) or supporting us on [Patreon](https://www.patreon.com/polyhaven/overview), make sure you follow the installation instructions in the readme carefully - it seems you did not rename the installed folder.

**Comment by RbBadGuy** [comment]
I Did Rename It

**Comment by RbBadGuy** [comment]
%appdata%\Blender Foundation\Blender Script Then Rename Right?

**Comment by RbBadGuy** [comment]
Or You Can Try Onther Way Too Before Installing Export The Zip Then Rename PolyHaven\PolyHaven Remove Version From Both The Compress It To Zip Again

**Comment by KillerJoxXx** [comment]
I have the same error and i can't fix it

**Comment by RbBadGuy** [comment]
> I Did Try Onther Way Too Before Installing. Export The Zip Then Rename PolyHaven\PolyHaven Remove Version From Both Then Compress It To Zip Again. I Am Saying This Only Solved My Problem



> I have the same error and i can't fix it
 did you try use this method?

**Comment by RbBadGuy** [comment]
export the zip go inside the folder if you downloaded and saved it to downloads it might be like this C\downloads\PolyHaven
then you will see onther poly haven folder inside remove the version polyhaven.0.0.0.0 remove that then rezip it

**Comment by KillerJoxXx** [comment]
That worked thank you

**Comment by RbBadGuy** [comment]
well np
