### ISSUE TITLE
"Fetch assets" error

### ISSUE THREAD

**Issue by notSushio** [Poly-Haven/polyhavenassets#55]
Coming up with a error code when clicking "Fetch assets" button.

![image](https://user-images.githubusercontent.com/126131360/220811333-d7480946-f45f-4251-a95d-f876609685ba.png)

**Comment by gregzaal** [comment]
Hi,

If you're not purchasing the add-on from the [Blender Market](https://blendermarket.com/products/poly-haven-asset-browser) or supporting us on [Patreon](https://www.patreon.com/polyhaven/overview), make sure you follow the installation instructions in the readme carefully - it seems you did not rename the installed folder.

**Comment by notSushio** [comment]
> Hi,
> 
> If you're not purchasing the add-on from the [Blender Market](https://blendermarket.com/products/poly-haven-asset-browser) or supporting us on [Patreon](https://www.patreon.com/polyhaven/overview), make sure you follow the installation instructions in the readme carefully - it seems you did not rename the installed folder.

I've renamed the folder it still comes up with the error

**Comment by gregzaal** [comment]
I can see in your screenshot posted above, the folder is named `polyhavenassets-main`, when it should be just `polyhavenassets`.

**Comment by notSushio** [comment]
> I can see in your screenshot posted above, the folder is named `polyhavenassets-main`, when it should be just `polyhavenassets`.

Thank you for the help, I just had to show my hidden files and go through the appdata to change the name, sorry for the inconvenience.
