### ISSUE TITLE
Unable to use addon

### ISSUE THREAD

**Issue by KillerJoxXx** [Poly-Haven/polyhavenassets#57]
**Describe the bug**
I can't install the addon and whenever I use the check box I get this error

![image](https://user-images.githubusercontent.com/126392968/221409421-05844b17-67d0-4e9b-810e-ac5ee9d1d4aa.png)

**Comment by gregzaal** [comment]
Hi,

If you're not purchasing the add-on from the [Blender Market](https://blendermarket.com/products/poly-haven-asset-browser) or supporting us on [Patreon](https://www.patreon.com/polyhaven/overview), make sure you follow the installation instructions in the readme carefully - it seems you did not rename the installed folder.
