### ISSUE TITLE
no panel to control texture resolution

### ISSUE THREAD

**Issue by D-Zuev** [Poly-Haven/polyhavenassets#58]
I don't have a panel "Texture Controls" in material properties

**Comment by gregzaal** [comment]
For bug reports, please use the [issue template](https://github.com/Poly-Haven/polyhavenassets/issues/new?assignees=&labels=&template=bug_report.md&title=) and provide all the necessary information to help me investigate the issue.

Please check the documentation and demo video for usage instructions: https://docs.polyhaven.com/en/guides/blender-addon
