### ISSUE TITLE
Asset misnamed

### ISSUE THREAD

**Issue by ThinkWithPbody** [Poly-Haven/polyhavenassets#59]
Model asset CashRegister_01 has child elements called CashRegister_01_body and CashRegister_011_drawer.

**Comment by ThinkWithPbody** [comment]
Also with this particular asset, the glass material in .png which takes up 5% of the surface area is taking up 5 times as much disk space as the main material which is stored in jpg. At that point, we may as well combine the two sets of textures and use .png for both so that fewer compression artifacts will be visible at lower resolutions. I'm still just starting to use the addon and its assets but inconsistencies like this I thought I should point out.

**Comment by gregzaal** [comment]
Hi again :)

Thanks for the feedback, we're certainly improving all the time and hope to have less inconsistencies like this in the future.
