### ISSUE TITLE
Can't change model resolution from material tab

### ISSUE THREAD

**Issue by MLSp3nce** [Poly-Haven/polyhavenassets#6]
Hello, I have just purchased the add-on and Ive been trying to increase the texture resolution of a couple models, specifically the cassette player and vintage grandfather clock. Whenever I try to use the drop-down menu to increase the resolution, no matter what resolution size, I would get the error shown below. This seems to only happen with the models. 

I am using Blender 3.4.0 Alpha 

![image](https://user-images.githubusercontent.com/57275043/187058187-3aaddae7-a334-4193-8360-64356a497950.png)

**Comment by gregzaal** [comment]
Hi :)

How are you adding the models into the scene? Using the default **Append (Reuse data)** option or something else?

![2022-08-29_11-44-26_blender](https://user-images.githubusercontent.com/5604661/187173521-948370a2-bcd4-4c54-b240-057dd864820c.png)

Can you show a screenshot of the panel where you are changing the resolution?

**Comment by MLSp3nce** [comment]
Hi, thanks for the response!
Yes, I am using Append (Reuse Data), and here is the panel
![image](https://user-images.githubusercontent.com/57275043/187271107-25f6d665-9183-4ed8-8ef2-90848f9076b7.png)

**Comment by gregzaal** [comment]
Ah ok! This is a bug when switching a model's resolution from the material tab. Rather use the object tab (orange square icon).

**Comment by MLSp3nce** [comment]
Happy to confirm it has been fixed! Thanks for the help!

**Comment by gregzaal** [comment]
Great! Thanks for checking!
