### ISSUE TITLE
Python / SSL bug - When downloading the library 

### ISSUE THREAD

**Issue by Laseussobonjour** [Poly-Haven/polyhavenassets#61]
Hi, 
I wanted to instal your addon but i cannot download the library of 3,3GB.
 I checked all the documentation and test everything but nothing work and i'm lost. It's at the moment of clicking on the ''Fetch asset on polyhaven.com''. 

 Here is the console output that i get:

```
Python: Traceback (most recent call last):
  File "/Users/gouin-lagreable/Library/Application Support/Blender/3.4/scripts/addons/polyhavenassets-main/operators/pull_from_polyhaven.py", line 282, in execute
    error, assets = get_asset_list(self.asset_type)
  File "/Users/gouin-lagreable/Library/Application Support/Blender/3.4/scripts/addons/polyhavenassets-main/utils/get_asset_list.py", line 15, in get_asset_list
    verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify
KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'

```

Of course, i checked if my blender app was updated. I'm on macOs system. 
Can you help me ? 

Thank you
Have a nice day.

Jérémy

**Comment by gregzaal** [comment]
Hi,

If you're not purchasing the add-on from the [Blender Market](https://blendermarket.com/products/poly-haven-asset-browser) or supporting us on [Patreon](https://www.patreon.com/polyhaven/overview), make sure you follow the installation instructions in the readme carefully.
