### ISSUE TITLE
cannot change resolution of HDRI or texture

### ISSUE THREAD

**Issue by Maffew1234** [Poly-Haven/polyhavenassets#64]
When I apply an HDRI there is no option to change the resolution in the world settings. this has disappeared and I don't know why. See screenshot. I can't get the console log to work, I'm sorry. using blender 3.5 

<img width="1728" alt="Screenshot 2023-04-22 at 13 24 00" src="https://user-images.githubusercontent.com/131527680/233784597-dc9bfd71-82e8-4346-9e36-e12953b2943b.png">

**Comment by gregzaal** [comment]
Hi there :) I see your asset browser is set to "Follow Preferences" mode. Can you try changing this to "Append (re-use data)" instead? If that solves it, then make sure to set this preference for the asset library so you don't need to do this every time.

![image](https://user-images.githubusercontent.com/5604661/233922345-e50cf9de-2684-49ee-b6ff-eef400902924.png)
