### ISSUE TITLE
Downloading assets stuck at 99%

### ISSUE THREAD

**Issue by Richap52** [Poly-Haven/polyhavenassets#69]
As in title, downloading the assets for the first time seems to have stopped at 99% having downloaded "yellow_field"

![Screenshot 2023-06-15 155641](https://github.com/Poly-Haven/polyhavenassets/assets/9778548/a29bb6df-5175-4e15-9c4e-58802ea5466b)

**Comment by gregzaal** [comment]
Hi :)

This can sometimes happen due to various connection issues - can you try closing Blender and retrying?

**Comment by Richap52** [comment]
Hi Greg,

All good now, thanks.

Please would you help with Another problem I don't understand.

Any asset I bring into a file is uneditable. I want to change material or make a small mesh change but all I can see is an empty collection within a collection. I have tried making single user or unlinking but the mesh just disappears.

Could you advise please.

Many thanks

Richard Chapman

**Comment by gregzaal** [comment]
Hi again, does this help? https://docs.polyhaven.com/en/guides/blender-addon#editing-models
