### ISSUE TITLE
Resolution Dropdown disappearing after save

### ISSUE THREAD

**Issue by NothingHereIsReal** [Poly-Haven/polyhavenassets#73]
**Describe the bug**

Running the latest version of Ploy Haven Assets 1.1.1 and Blender 3.6 LTS, add an asset - HDRI for example, save the file, after the save the Resolution Dropdown in the World Properties panel disappears and the panels below scroll up.

**Console log**
Start blender from a command prompt/terminal (https://docs.blender.org/manual/en/latest/advanced/command_line/launch/index.html), reproduce the issue and paste the entire console output here:

```
C:\Program Files\Blender Foundation\Blender 3.6>blender.exe
Read prefs: "C:\Users\paul\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend"
TheGrove11
P19200:07:46:32:botaniq_full:INFO: Logger for "botaniq_full" initialized in "C:\Users\paul\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\botaniq_full\__init__.py" -----
P19200:07:46:32:polib:INFO: Logger for "polib" initialized in "C:\Users\paul\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\botaniq_full\python_deps\polib\__init__.py" -----
P19200:07:46:32:mapr:INFO: Logger for "mapr" initialized in "C:\Users\paul\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\botaniq_full\python_deps\mapr\__init__.py" -----
botaniq install dir autodetected as C:\Users\paul\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\botaniq_full (big zip embedded)
Info: Total files 5 | Changed 5 | Failed 0
Saved session recovery to "C:\Users\paul\AppData\Local\Temp\quit.blend"

Blender quit

C:\Program Files\Blender Foundation\Blender 3.6>
```

**To Reproduce**
Steps to reproduce the behaviour, starting from an empty scene in Blender:
1. Open Asset browser
2. Drag HDRI to the viewport
3. Select World Properties
4. Notice resolution dropdown is visible
5. Save scene to file
6. World Properties is now missing resolution dropdown

**Expected behaviour**
Resolution dropdown should remain visible after save

**Screenshots**

![image](https://github.com/Poly-Haven/polyhavenassets/assets/1449700/daac6f9d-a76b-4ffd-b30c-723643321230)
![image](https://github.com/Poly-Haven/polyhavenassets/assets/1449700/6316b7c4-bf0a-4957-8b45-c8962e3b37c8)

**Additional context**
I disabled all addons and it still failed. I tried on a new install of 3.6 with no addons and the behaviour was the same. I was able to revert to 1.0.6 and the behaviour returned to normal with that version.

**Comment by gregzaal** [comment]
Hi, thanks for the report!

I have a suspicion this is due to the new relative path options for asset libraries, but I'm without internet at the moment so I'll only be able to test this next week.

**Comment by gregzaal** [comment]
Managed to debug this, indeed it was caused by assets (and asset libraries) being able to have relative paths in 3.6.

@NothingHereIsReal Would you mind updating to the master version with the button in the preferences and testing there? Please also try to download some new assets and swap resolutions around. I believe it should work now but a second opinion doesn't hurt :)

![SCR-20230701-qtr](https://github.com/Poly-Haven/polyhavenassets/assets/5604661/acbdd841-9351-4050-9e1e-99c8ab4c2a3f)

**Comment by NothingHereIsReal** [comment]
Several problems

1. The Install master resulted in a 404 error: 
<img width="232" alt="image" src="https://github.com/Poly-Haven/polyhavenassets/assets/1449700/5f912071-84a7-4ac8-a236-d422b3afc815">

I went to Github and downloaded it manually. Uninstalling and reinstalling it then appears to work and the first HDRi loads and the dropdown remains in the panel after saves. However any attempt to change the resolution briefly shows the **Downloading** message but nothing happens. The selection on the dropdown remains the same and the HDRi is unaltered.

**Comment by NothingHereIsReal** [comment]
I've just thought that the 404 error and the non-updating HDRis could be related if there was a server or network error. I'm not aware of any issues at my end though.

**Comment by NothingHereIsReal** [comment]
And, when trying to fetch new assets this happened:
![image](https://github.com/Poly-Haven/polyhavenassets/assets/1449700/3e1141f0-7325-4f3f-8053-e14908c87c87)

**Comment by gregzaal** [comment]
That error (and probably the other ones too) is caused by a broken installation when downloading the zip manually from Github. To fix this you can rename the installed folder `polyhavenassets-main` to just `polyhavenassets`.

Please confirm that the installed version says 1.1.2 and not 1.1.1 before testing.

**Comment by NothingHereIsReal** [comment]
Thanks, Greg. That sorted it. It all works as expected now.

Paul

**Comment by gregzaal** [comment]
Awesome thanks for checking 👍 Just pushed v1.1.2
