### ISSUE TITLE
Nothing in my Browser

### ISSUE THREAD

**Issue by Ramirez8052** [Poly-Haven/polyhavenassets#75]
Nothing displayed 
I downloaded add-on and followed the procedure, but nothing appears in the Browser. I have Blender version 3.3. 

![PolyHaven_problem](https://github.com/Poly-Haven/polyhavenassets/assets/138364749/892f0f57-4779-4a0f-9a04-63f5f7e0d44b)
![PolyHaven_problem2](https://github.com/Poly-Haven/polyhavenassets/assets/138364749/22c404f3-e536-4da6-812d-6efd085eedb0)

I don't know what to do?

**Comment by gregzaal** [comment]
Hi, thanks for the catch. I've just pushed out a fix for this issue in v1.1.3 which you can update to from the add-on's user preferences.
