### ISSUE TITLE
Python: Traceback (most recent call last):   File "C:\Users\home\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\polyhavenassets-main\operators\pull_from_polyhaven.py", line 285, in execute     error, assets = get_asset_list(self.asset_type)   File "C:\Users\home\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\polyhavenassets-main\utils\get_asset_list.py", line 15, in get_asset_list     verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'

### ISSUE THREAD

**Issue by grannyyt** [Poly-Haven/polyhavenassets#76]
how to fix??? 
Python: Traceback (most recent call last):
  File "C:\Users\home\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\polyhavenassets-main\operators\pull_from_polyhaven.py", line 285, in execute
    error, assets = get_asset_list(self.asset_type)
  File "C:\Users\home\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\polyhavenassets-main\utils\get_asset_list.py", line 15, in get_asset_list
    verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify
KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'

**Comment by gregzaal** [comment]
Hi, if you're not purchasing the add-on from the [Blender Market](https://blendermarket.com/products/poly-haven-asset-browser) or supporting us on [Patreon](https://www.patreon.com/polyhaven/overview), make sure you follow the installation instructions in the readme carefully. The add-on must be downloaded from the releases page.
