### ISSUE TITLE
Issue when trying to fetch assets

### ISSUE THREAD

**Issue by willstefany** [Poly-Haven/polyhavenassets#77]
I followed the instructions in the video and readme and got to fetch assets where it gives me an error. I renamed the zip file just polyhavenassets but that did nothing. The file path is named Poly Haven

Error message:

bpy.ops.pha.pull_from_polyhaven(asset_type="all")

Python: Traceback (most recent call last):
  File "C:\Users\Will\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\polyhavenassets-main\operators\pull_from_polyhaven.py", line 285, in execute
    error, assets = get_asset_list(self.asset_type)
  File "C:\Users\Will\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\polyhavenassets-main\utils\get_asset_list.py", line 15, in get_asset_list
    verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify
KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'

Thanks

**Comment by gregzaal** [comment]
Hi, if you're not purchasing the add-on from the [Blender Market](https://blendermarket.com/products/poly-haven-asset-browser) or supporting us on [Patreon](https://www.patreon.com/polyhaven/overview), make sure you follow the installation instructions in the readme carefully. The add-on must be downloaded from the releases page.

**Comment by willstefany** [comment]
I got it, thanks
