### ISSUE TITLE
Cannot enable addon

### ISSUE THREAD

**Issue by clovelt** [Poly-Haven/polyhavenassets#8]
Latest version of Blender off Steam, installed the zip and received this message when attempting to enable the plugin:
![imagen](https://user-images.githubusercontent.com/8393870/187976154-ddf8b1f7-22ec-4d17-b3d1-50e5235848cf.png)

**Comment by gregzaal** [comment]
Hi, it looks like you skipped a step in the install instructions (renaming the folder to remove the version number) 🙂
