### ISSUE TITLE
Error: Unable to execute 'Toggle Edit Mode', error changing modes

### ISSUE THREAD

**Issue by Miautomat** [Poly-Haven/polyhavenassets#85]
**Describe the bug**
After "making an instance real" I cannot enter Edit Mode and face the Error as shown in the Console Log.

**Console log**
```
C:\Program Files\Blender Foundation\Blender 3.6>blender
Read prefs: "C:\Users\<redacted>\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend"
Info: Deleted 3 object(s)

Error: Unable to execute 'Toggle Edit Mode', error changing modes
```

**To Reproduce**
Steps to reproduce the behavior, starting from an empty scene in Blender:
1. Go to 'Asset Browser'
2. Drag any Item into the Scene
3. Select Object
4. Click 'Object > Apply > Make Instance Real'
5. Select Object
6. Toggle Edit Mode
7. Error occurs

**Expected behavior**
I expect to be able to enter edit mode, change Materials etc. as if it was a real independent object.

**Additional context**
I noticed that the materials are still linked and not editable, see: 
![image](https://github.com/Poly-Haven/polyhavenassets/assets/5058960/3ff55770-bf8b-47d8-a3c7-801f003201f7)
You can work around that by iteratively creating Library Overrides (first for the collection and then specifically for the object(s))

Blender version: 3.6.2
OS: Windows 10 Pro 19045.3448
Polyhaven Addon Version: 1.1.5

**Comment by Miautomat** [comment]
Just like in [Issue#84](https://github.com/Poly-Haven/polyhavenassets/issues/84) I found the culprit after checking out some older issues in this project:
The Default Import Method was set to "Link" rather than "Append (Reuse Data)".

Hence, I'm closing this issue.

**Comment by Miautomat** [comment]
I suggest adding an entry to the troubleshooting for the Import Method.
I would do it myself but unfortunately I have a very very tight schedule for my Blender project right now.

**Comment by gregzaal** [comment]
Will do, thanks!
