### ISSUE TITLE
Polyhaven addon not enabling 

### ISSUE THREAD

**Issue by Johnb113** [Poly-Haven/polyhavenassets#86]
Trying to download and install polyhaven but every time I try to click to enable it, I get the error saying it is already a registered subclass
![IMG_7677](https://github.com/Poly-Haven/polyhavenassets/assets/145613039/ba3f016d-74f3-469b-869e-afba4fb17642)
. Blendr is up to date (9/20/23) as well as the polyhaven add on
/

**Comment by gregzaal** [comment]
This sounds like an activation/registration issue, usually solved by just restarting Blender. Does that help?

**Comment by Johnb113** [comment]
I've restarted blender a multitude of times as well as reinstalled it and the zip file. Your website says it's because blendr is out of date but I have the most recent 3.6.2 version off their website. I will give it another try tomorrow in the morning and keep you posted.

**Comment by gregzaal** [comment]
OK, it's possible that multiple copies of the add-on are installed then. Can you check if there is more than one `polyhavenassets...` folder in `C:\Users\John\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons`?

Otherwise we'll need to debug the issue further by starting Blender with factory defaults and seeing if the issue persists.

**Comment by Johnb113** [comment]
OK, I have found polyhaven assets folder in the roaming. Should there also
be an int.py file below it?

**Comment by Johnb113** [comment]
There is only one polyhaven aseets so I can delete it and try again but do
I still need to retain the int.py file below it?

**Comment by Johnb113** [comment]
![Screenshot 2023-09-21 124107-](https://github.com/Poly-Haven/polyhavenassets/assets/145613039/5edf804a-26e9-4214-b414-9ce36e2af95e)

**Comment by Johnb113** [comment]
Tried again. Deleted the files in the app data, deleted blender and redownloaded everything again. Still the same issue

**Comment by Johnb113** [comment]
Finally figured it out. I needed the cycle render engine enabled in order to enable the poly haven add-on

**Comment by Johnb113** [comment]
Thank you for reaching out

**Comment by gregzaal** [comment]
Ah great, thanks for letting me know :) If you have any more issues, please use the provided bug report template when opening an issue as that helps weed out these sorts of problems faster.
