### ISSUE TITLE
403 Error when fetching assets

### ISSUE THREAD

**Issue by Demoniak69** [Poly-Haven/polyhavenassets#87]
When clicking on Fetch Assets, it makes folders and places thumbnails (.webp files)
Unfortunately, it does not download the models.
I have tried the alternate site checkbox as well, with the same results.
The info log does not say much, only:
Downloading in background...
Error retrieving https://dl.polyhaven.org/file/ph-assets/Models/blend/1k/ArmChair_01/ArmChair_01_1k.blend, status code: 403
Error retrieving https://dl.polyhaven.org/file/ph-assets/Models/blend/1k/CheeseBox_01/CheeseBox_01_1k.blend, status code: 403

**Comment by gregzaal** [comment]
Hi there,

Status code 403 means "permission denied", which is strange since our download URLs obviously do not require any special permissions on our side. Perhaps there is some network configuration or firewall issue on your machine?

Are you unable to download assets manually from the website as well? E.g.: https://polyhaven.com/a/ArmChair_01

**Comment by Demoniak69** [comment]
I tested this today, I had no issue downloading an HDRI from the website and using it as a background in my scene. When i tried again to Fetch Assets, I got the same 403 error for every file :'(

**Comment by gregzaal** [comment]
If you click the download URL directly, does it download fine or also result in a 403 error? (e.g. https://dl.polyhaven.org/file/ph-assets/Models/blend/1k/ArmChair_01/ArmChair_01_1k.blend)

If not, you can try changing your DNS to either Google (8.8.8.8) or Cloudflare (1.1.1.1) which could help. I would also try restarting your machine and your router which may be caching these errors.

Unfortunately I have received no other reports like this recently and cannot see any unusual behaviour on the servers.

**Comment by gregzaal** [comment]
Closing due to lack of response :)
