### ISSUE TITLE
context.space_data.params.asset_library_ref now context.space_data.params.asset_library_reference

### ISSUE THREAD

**Issue by blastframe** [Poly-Haven/polyhavenassets#89]
Thank you for your wonderful Poly-Haven Assets add-on! It is currently throwing errors in Blender 4.0 Beta because of a change to the Python API. `asset_library_ref` is now `asset_library_reference`

[https://projects.blender.org/blender/blender/commit/974d70918b582cff41b12b29105a0f85786b27fe](https://projects.blender.org/blender/blender/commit/974d70918b582cff41b12b29105a0f85786b27fe)

Your add-on uses `asset_library_ref` in [asset_lib_support.py](https://github.com/Poly-Haven/polyhavenassets/blob/5a25943bf53cf7142e6d6a4ad4d29d2fc01e7fac/ui/asset_lib_support.py#L6), [asset_lib_titlebar.py](https://github.com/Poly-Haven/polyhavenassets/blob/5a25943bf53cf7142e6d6a4ad4d29d2fc01e7fac/ui/asset_lib_titlebar.py#L7), and [PT_sidebar.py](https://github.com/Poly-Haven/polyhavenassets/blob/5a25943bf53cf7142e6d6a4ad4d29d2fc01e7fac/ui/PT_sidebar.py#L30)

**Comment by gregzaal** [comment]
Thanks for the report, fixed in 0ae76e55 !
