### ISSUE TITLE
Polyhaven Addon not working / visible in Blender UI

### ISSUE THREAD

**Issue by grootlicht** [Poly-Haven/polyhavenassets#92]
**Describe the bug**
The Polyhaven Addon not working / visible in Blender UI. I've have tried several solutions:
- remove and reinstall addon
- installed previous versions
- other library folder locations
- downloaded the zip file again
- options alternative CDN and Disable SSL 
- disabled other addons

**Console log**
Sorry, the command terminal wouldn't give me acces to the Blemder directory : /

Working on a Windows 10 system, see attached system-info.txt

```
PASTE CONSOLE OUTPUT HERE
```

**To Reproduce**
Steps to reproduce the behavior, starting from an empty scene in Blender:
1. Go to 'preferences > addons > Poly Haven Assets'
2. Click on 'Revalidate All Assets' > 'Fetch assets from polyhaven.com'
3. info prompt: 'Revalidated 0 assets ' 

**Expected behavior**

**Screenshots**

**Additional context**
![PolyHaven-Bug-02](https://github.com/Poly-Haven/polyhavenassets/assets/2239712/876d6b92-5a05-4a2e-9f3c-1b3a4420b3b3)
[system-info.txt](https://github.com/Poly-Haven/polyhavenassets/files/13162979/system-info.txt)

**Comment by gregzaal** [comment]
Hi there :)

Just to confirm, in your screenshot you are showing the "All" group of asset libraries, not just the Poly Haven library. If you select the Poly Haven Library, do you see the Fetch Assets button, and does it also not download any assets?

![image](https://github.com/Poly-Haven/polyhavenassets/assets/5604661/90412a87-e219-44f9-9a49-94c8bc73f461)
