### ISSUE TITLE
polyhaven clashing with Pidgeon Tool bag 

### ISSUE THREAD

**Issue by KelvinLaw-jpg** [Poly-Haven/polyhavenassets#94]
**Describe the bug**
I was trying to install the pidgeon tool bag and it has the add on is not installing due to a bag in polyhaven add on. 

**Console log**
Start blender from a command prompt/terminal (https://docs.blender.org/manual/en/latest/advanced/command_line/launch/index.html), reproduce the issue and paste the entire console output here:

```
AttributeError: 'FileAssetSelectParams' object has no attribute 'asset_library_ref'. Did you mean: 'asset_library_reference'?
Traceback (most recent call last):
  File "C:\Users\Utimate_RGB_Gamer\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Kitbash3D_Cargo\cargo.py", line 610, in modal
    def modal(self, context, event):
```

**To Reproduce**
Steps to reproduce the behavior, starting from an empty scene in Blender:

**Expected behavior**
Add on should nicely install

**Screenshots**
![Capture](https://github.com/Poly-Haven/polyhavenassets/assets/73468336/f7c154a3-8c25-4074-876a-932dcc5fa468)
![Capture](https://github.com/Poly-Haven/polyhavenassets/assets/73468336/b1ea23d6-7012-4502-9476-b28480a36af9)

**Additional context**

**Comment by gregzaal** [comment]
Hi there,

This bug was fixed in version 1.1.6. `asset_library_ref` was available in Blender 3.6 and renamed to `asset_library_reference` in Blender 4.0. The add-on (if it's version 1.1.6 or later) will support both.
