### ISSUE TITLE
i ha ve this message : Python: Traceback (most recent call last):   File "/Users/xxx/Library/Application Support/Blender/4.0/scripts/addons/polyhavenassets-main/operators/pull_from_polyhaven.py", line 294, in execute     error, assets = get_asset_list(self.asset_type)   File "/Users/n.cros/Library/Application Support/Blender/4.0/scripts/addons/polyhavenassets-main/utils/get_asset_list.py", line 15, in get_asset_list     verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'

### ISSUE THREAD

**Issue by papout-42** [Poly-Haven/polyhavenassets#98]
**Describe the bug**

**Console log**
Start blender from a command prompt/terminal (https://docs.blender.org/manual/en/latest/advanced/command_line/launch/index.html), reproduce the issue and paste the entire console output here:

```
PASTE CONSOLE OUTPUT HERE
```

**To Reproduce**
Steps to reproduce the behavior, starting from an empty scene in Blender:

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by gregzaal** [comment]
Hi, if you're not purchasing the add-on from the [Blender Market](https://blendermarket.com/products/poly-haven-asset-browser) or supporting us on [Patreon](https://www.patreon.com/polyhaven/overview), make sure you follow the installation instructions in the readme carefully. The add-on must be downloaded from the releases page.
